// <auto-generated />
using System;
using FundLib.Model.DataBaseModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FundLib.Migrations
{
    [DbContext(typeof(FundDbContext))]
    [Migration("20210729090426_removefunditem")]
    partial class removefunditem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("FundLib.Model.FundDetail", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("TEXT");

                    b.Property<double?>("assets")
                        .HasColumnType("REAL");

                    b.Property<double?>("bondPercent")
                        .HasColumnType("REAL");

                    b.Property<double?>("cashPercent")
                        .HasColumnType("REAL");

                    b.Property<string>("ftype")
                        .HasColumnType("TEXT");

                    b.Property<string>("lastTime")
                        .HasColumnType("TEXT");

                    b.Property<double?>("monery")
                        .HasColumnType("REAL");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<double?>("otherPercent")
                        .HasColumnType("REAL");

                    b.Property<double?>("stockPercent")
                        .HasColumnType("REAL");

                    b.HasKey("code");

                    b.ToTable("FundDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
