// <auto-generated />
using FundLib.Model.DataBaseModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FundLib.Migrations
{
    [DbContext(typeof(FundDbContext))]
    partial class FundDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("FundLib.Model.DataBaseModel.FundItem", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("TEXT");

                    b.HasKey("code");

                    b.ToTable("FundItem");
                });
#pragma warning restore 612, 618
        }
    }
}
